name: Generate spaced AGENTS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run generator
        run: |
          python3 scripts/spaced_repetition.py
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add AGENTS.md
            git commit -m "chore: update AGENTS spaced repetition [skip-agent]" && git push
          fi
